[package]
name = "rz_frzbn"
version = "0.1.0"
authors = ["l1npengtul l1npengtul <l1npengtul@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.8"

[lib]
crate-type=["cdylib"]

